export default [
    {
        "brandName": "华晨宝马",
        "activityInfoList": [],
        "brandId": 545,
        "styleList": [
            {
                "isBuy": 0,
                "brandName": "华晨宝马",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "29.39-40.59",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马3系",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 545,
                "logo": "http://pic.tuanche.com/car/20200511/1053/c25ad6dc185b4ebeb8950c46c4b91912.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 169,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "华晨宝马",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "39.28-47.58",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马X3",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 545,
                "logo": "http://pic.tuanche.com/car/20190820/2000/fb36171a3f1a4f3e8609ae44f74017dc.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 32678,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "华晨宝马",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "42.19-54.69",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马5系",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 545,
                "logo": "http://pic.tuanche.com/car/20181228/1634/4e0445120e5a4176b7a3128bf827be30.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 168,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "华晨宝马",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "27.98-33.98",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马X1",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 545,
                "logo": "http://pic.tuanche.com/car/20181228/1634/293fbe4645f84f9e912d989e425acb6f.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 308,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "华晨宝马",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "20.58-24.68",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马1系",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 545,
                "logo": "http://pic.tuanche.com/car/20181228/1634/ae738e4c4a714af6bce8df86078c6061.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 32297,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "华晨宝马",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "49.99-53.69",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马5系新能源",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 545,
                "logo": "http://pic.tuanche.com/car/20181228/1634/2f14b65643174ac49a0c1cfb309af7a3.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 32599,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "华晨宝马",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "28.58-32.98",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马X2",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 545,
                "logo": "http://pic.tuanche.com/car/20191015/1701/bf8606a4874b423e8796af8b198b026f.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 85605,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "华晨宝马",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "39.98",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马X1新能源",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 545,
                "logo": "http://pic.tuanche.com/car/20181228/1634/67e3cd57df67448098dc42fd5ad4dc75.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 32333,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "华晨宝马",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "39.99-43.99",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马iX3",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 545,
                "logo": "http://pic.tuanche.com/car/20200817/1700/5eb3411b610a4929bc725db4e28db230.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 105758,
                "descriptionStr": "",
                "fuelStr": "暂无"
            }
        ],
        "brandPic": "http://pic.tuanche.com/car/20200416/1508/f5b0badd01bc4f22bf5f484b08b48f12.jpg"
    },
    {
        "brandName": "宝马(进口)",
        "activityInfoList": [],
        "brandId": 195,
        "styleList": [
            {
                "isBuy": 0,
                "brandName": "宝马(进口)",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "69.99-83.49",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马X5",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 195,
                "logo": "http://pic.tuanche.com/car/20181228/1634/d8d7d448fae1454e8ca8a2cf21df2ba9.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 311,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "宝马(进口)",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "26.38-33.98",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马2系",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 195,
                "logo": "http://pic.tuanche.com/car/20181228/1634/01ed99d76f08403aa89e51ef5b9b60b6.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 13164,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "宝马(进口)",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "76.69-93.19",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马X6",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 195,
                "logo": "http://pic.tuanche.com/car/20181228/1635/359c5429239a443eb03de49ee50d1d81.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 286,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "宝马(进口)",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "82.80-261.20",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马7系",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 195,
                "logo": "http://pic.tuanche.com/car/20181228/1634/64996d4c080949e7a9ee82ba3b1dba5a.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 299,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "宝马(进口)",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "48.88-63.38",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马Z4",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 195,
                "logo": "http://pic.tuanche.com/car/20150921/14428114492711708_s.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 316,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "宝马(进口)",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "45.59-55.29",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马X4",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 195,
                "logo": "http://pic.tuanche.com/car/20181228/1634/702dda0eb7da4b4aa2769840ea826602.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 13327,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "宝马(进口)",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "42.39-60.39",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马5系(进口)",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 195,
                "logo": "http://pic.tuanche.com/car/20181228/1635/ed72c89ef13c42699c92f48d51a75446.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 13477,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "宝马(进口)",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "35.98-43.98",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马3系GT",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 195,
                "logo": "http://pic.tuanche.com/car/20181228/1634/ab81cf5608414fc5b4b3f6439c22fb6e.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 13812,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "宝马(进口)",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "85.99",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马X5新能源",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 195,
                "logo": "http://pic.tuanche.com/car/20190826/2000/8f5b9cc01c35449cab25c11be4befc1a.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 32334,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "宝马(进口)",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "58.39-68.39",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马6系GT",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 195,
                "logo": "http://pic.tuanche.com/car/20181228/1634/720cea3af1eb42da9f2f03ec42f415ff.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 32538,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "宝马(进口)",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "35.98-55.88",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马4系",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 195,
                "logo": "http://pic.tuanche.com/car/20181228/1634/dfbd55b421aa47f98a46ac65a9a62c8e.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 13131,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "宝马(进口)",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "26.38-29.98",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马2系多功能旅行车",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 195,
                "logo": "http://pic.tuanche.com/car/20181228/1634/ae434fc9932041999b7ed7b98579d8c9.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 32053,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "宝马(进口)",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "96.20-126.80",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马8系",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 195,
                "logo": "http://pic.tuanche.com/car/20190911/1501/53c1b3acc56140078539f9b870b4dc82.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 84249,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "宝马(进口)",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "100.00-178.80",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马X7",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 195,
                "logo": "http://pic.tuanche.com/car/20190426/2005/80f7bb47e36846e8bef00e6e8163276d.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 85110,
                "descriptionStr": "",
                "fuelStr": "暂无"
            }
        ],
        "brandPic": "http://pic.tuanche.com/car/20200416/1508/d455b93411474662809cb8b44537b5a0.jpg"
    },
    {
        "brandName": "宝马M",
        "activityInfoList": [],
        "brandId": 196,
        "styleList": [
            {
                "isBuy": 0,
                "brandName": "宝马M",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "143.89",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马M5",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 196,
                "logo": "http://pic.tuanche.com/car/20181228/1634/76312c561eee49cca09dca37697cd574.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 32697,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "宝马M",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "196.80-256.80",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马M8",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 196,
                "logo": "http://pic.tuanche.com/car/20190911/1501/6ee4b611a6b54149ad9d5f4ee7f302d0.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 84272,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "宝马M",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "83.59-89.99",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马X3 M",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 196,
                "logo": "http://pic.tuanche.com/car/20190905/1153/cc945ea7adcb431aa536517c3df69e5f.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 85486,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "宝马M",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "143.89",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马X5 M",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 196,
                "logo": "http://pic.tuanche.com/car/20181228/1634/ffb530a6f9bf40f591e8fea284254b33.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 32699,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "宝马M",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "84.99-89.99",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马M3",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 196,
                "logo": "http://pic.tuanche.com/car/20181228/1634/2ee8811ff5e84be78b9cff478efb22fe.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 32695,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "宝马M",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "87.99-99.99",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马M4",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 196,
                "logo": "http://pic.tuanche.com/car/20181228/1634/3e1c8662688f4959b79c3baceb26c929.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 32696,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "宝马M",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "146.89",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马X6 M",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 196,
                "logo": "http://pic.tuanche.com/car/20181228/1634/afe73b692adb44beba87fa8f2cc9c0f0.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 32700,
                "descriptionStr": "",
                "fuelStr": "暂无"
            },
            {
                "isBuy": 0,
                "brandName": "宝马M",
                "firmBrandId": 0,
                "identify": 0,
                "manNum": 0,
                "prefix": "已有",
                "factoryPrice": "86.59-92.99",
                "ecLable": "",
                "isNew": 0,
                "styleName": "宝马X4 M",
                "pricePrefix": "厂商价：",
                "type": 0,
                "price": "",
                "brandId": 196,
                "logo": "http://pic.tuanche.com/car/20190905/1153/9f0fe129e1e245e98a50af8193aafad4.jpg",
                "displacement": "暂无",
                "priceSuffix": "万",
                "adInfo": "",
                "id": 85487,
                "descriptionStr": "",
                "fuelStr": "暂无"
            }
        ],
        "brandPic": "http://pic.tuanche.com/car/20200416/1508/f35566eeac384a30bba5e10f3f105dbf.jpg"
    }
]